[environments.production.services.lockr-backend]

[environments.production.services.lockr-backend.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[environments.production.services.lockr-backend.deploy]
startCommand = "npm run migrate && node server.js"
healthcheckPath = "/health" 